name: Go Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build http_server and http_client
        run: |
          mkdir -p build/${{ matrix.os }}_${{ matrix.arch }}
          GOOS=${{ matrix.os == 'ubuntu-latest' && 'linux' || 'darwin' }} GOARCH=${{ matrix.arch }} go build -o build/${{ matrix.os }}_${{ matrix.arch }}/http_server http_server/main.go
          GOOS=${{ matrix.os == 'ubuntu-latest' && 'linux' || 'darwin' }} GOARCH=${{ matrix.arch }} go build -o build/${{ matrix.os }}_${{ matrix.arch }}/http_client http_client/main.go

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.os }}-${{ matrix.arch }}
          path: build/${{ matrix.os }}_${{ matrix.arch }}/